version: '3'

services:
  cqhttp:
    image: richardchien/cqhttp:latest
    ports:
      - "9005:9000"
      - "5700:5700"
    environment:
#      - COOLQ_ACCOUNT=3187545268
#      - CQHTTP_POST_URL=http://httpserver:8085
      - CQHTTP_SERVE_DATA_FILES=yes
      - CQHTTP_USE_HTTP=yes
      - CQHTTP_POST_MESSAGE_FORMAT=array
      - port=5700
#    volumes:
#      # you should set your config in this dir
#      # if you continues run this, something bad may happens
#      - ./coolq:/home/user/coolq
#      - ./config:/home/user/coolq/app/io.github.richardchien.coolqhttpapi/config
#      debug with host mode
#    network_mode: "host"
#     # RSSHUB 旧的配置
#    extra_hosts:
#      - "httpserver:101.132.121.41"
  httpserver:
    volumes:
      - ~/coolq:/home/user/coolq
      - ./log:/home/user/log
    links:
      - cqhttp
#    environment:
#      - GIN_MODE=release
    build: ./qqbot
    ports:
      - "8085:8085"
    depends_on:
      - cqhttp
      - rsshub

  front-page:
    build:
      ./qqbot-frontend
    depends_on:
      - httpserver
    ports:
      - "8083:80"

  rsshub:
    image: diygod/rsshub:latest



